### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by tiansiyuan** [princeton-vl/RAFT#164]
python demo.py --model=models/raft-things.pth --path=demo-frames

Traceback (most recent call last):
  File "/home/jovyan/RAFT/demo.py", line 75, in <module>
    demo(args)
  File "/home/jovyan/RAFT/demo.py", line 62, in demo
    flow_low, flow_up = model(image1, image2, iters=20, test_mode=True)
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/RAFT/core/raft.py", line 100, in forward
    fmap1, fmap2 = self.fnet([image1, image2])        
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/RAFT/core/extractor.py", line 176, in forward
    x = self.conv1(x)
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by AzulYang** [comment]
Same problem,Have you known the reason ?

**Comment by tiansiyuan** [comment]
> Same problem,Have you known the reason ?

Nope
