### ISSUE TITLE
Trained Model Load ERROR.

### ISSUE THREAD

**Issue by DunguTmp** [princeton-vl/RAFT#23]
When running the demp.py as the README file,  I meet the error as followed. It seesm that your provided trained models may contains zip magic number. Are there some slutions to deal with this error.

(/home/anaconda3/envs/torch-1.0) l:/mnt/workspace/gitlab/RAFT-master$ python demo.py --model=/mnt/workspace/github/RAFT-master/models/raft-things.pth --path=demo-frames
Traceback (most recent call last):
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ild_tens'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 2294, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 1090, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 1032, in frombuf
    chksum = nti(buf[148:156])
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/site-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 1586, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 1616, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 1479, in __init__
    self.firstmember = self.next()
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/tarfile.py", line 2306, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 79, in <module>
    demo(args)
  File "demo.py", line 52, in demo
    model.load_state_dict(torch.load(args.model))
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/torch-1.0/lib/python3.6/site-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /mnt/workspace/github/RAFT-master/models/raft-things.pth is a zip archive (did you mean to use torch.jit.load()?)

**Comment by xiaobeikankan** [comment]
I'm going through the same problem.
RuntimeError: /mnt/workspace/github/RAFT-master/models/raft-things.pth is a zip archive (did you mean to use torch.jit.load()?)

**Comment by DunguTmp** [comment]
> I'm going through the same problem.
> RuntimeError: /mnt/workspace/github/RAFT-master/models/raft-things.pth is a zip archive (did you mean to use torch.jit.load()?

This error will not occur if you update your pytorch version to 1.6.0.
However, due to the restriction of reality situation, we can only use the pytorch version of 1.3.1.  I need to find a new solution to fix this.

**Comment by zachteed** [comment]
The models are not compatible with Pytorch < 1.6 due to changes in the zipfile serialization. You can download converted models with work with earlier version from here: [models-no-zip](https://drive.google.com/file/d/1OuzRuP9F-KWPCXbnSQ0LPBUwt5E-J5Qg/view?usp=sharing)

**Comment by DunguTmp** [comment]
> The models are not compatible with Pytorch < 1.6 due to changes in the zipfile serialization. You can download converted models which work with earlier version from here: [models-no-zip](https://drive.google.com/file/d/1OuzRuP9F-KWPCXbnSQ0LPBUwt5E-J5Qg/view?usp=sharing)

Thanks for ur share.

**Comment by btwbtm** [comment]
Hi. Could you please provide the non-zip version of raft-small? Thx!

**Comment by SSJIACV** [comment]
> Hi. Could you please provide the non-zip version of raft-small? Thx!

Hi, do you get the non-zip version of raft-small?  I also need
