### ISSUE TITLE
Running the demo with --alternate_corr fails

### ISSUE THREAD

**Issue by christian-rauch** [princeton-vl/RAFT#86]
Running the demo with `--alternate_corr`:
```
python demo.py --model=models/raft-things.pth --path=demo-frames --alternate_corr
```
results in:
```
Traceback (most recent call last):
  File "demo.py", line 75, in <module>
    demo(args)
  File "demo.py", line 62, in demo
    flow_low, flow_up = model(image1, image2, iters=20, test_mode=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "core/raft.py", line 124, in forward
    corr = corr_fn(coords1) # index correlation volume
  File "core/corr.py", line 86, in __call__
    corr, = alt_cuda_corr.forward(fmap1_i, fmap2_i, coords_i, r)
AttributeError: module 'alt_cuda_corr' has no attribute 'forward'
```

**Comment by christian-rauch** [comment]
Ok, I forgot to compile the `alt_cuda_corr` module but the `import alt_cuda_corr` was still successful.

Compiling via `python3 setup.py install --user` inside `alt_cuda_corr` does the trick.

I would recommend doing the `import alt_cuda_corr` only if the `AlternateCorrBlock` is used and throw an error if the module has not been compiled.

**Comment by plateau1** [comment]
> Ok, I forgot to compile the `alt_cuda_corr` module but the `import alt_cuda_corr` was still successful.
> 
> Compiling via `python3 setup.py install --user` inside `alt_cuda_corr` does the trick.
> 
> I would recommend doing the `import alt_cuda_corr` only if the `AlternateCorrBlock` is used and throw an error if the module has not been compiled.

May I ask, after using this module, will the prediction time be faster?

**Comment by christian-rauch** [comment]
> May I ask, after using this module, will the prediction time be faster?

No. According to the [documentation](https://github.com/princeton-vl/RAFT#optional-efficent-implementation) this only reduces the amount of memory:
> Note, this implementation is somewhat slower than all-pairs, but uses significantly less GPU memory during the forward pass.

**Comment by Ellsionjeep** [comment]
> > May I ask, after using this module, will the prediction time be faster?
> 
> No. According to the [documentation](https://github.com/princeton-vl/RAFT#optional-efficent-implementation) this only reduces the amount of memory:
> 
> > Note, this implementation is somewhat slower than all-pairs, but uses significantly less GPU memory during the forward pass.

**Comment by Ellsionjeep** [comment]
> > RuntimeError: Error compiling objects for extension
> 
> Can you give a more detailed error message? What exactly happens when you do `cd alt_cuda_corr && python3 setup.py install --user && cd ..`?

like this 
![image](https://user-images.githubusercontent.com/55690137/136876035-f7617064-0edc-4036-9ae8-8d284d788506.png)

**Comment by christian-rauch** [comment]
This error is in one of the torch scripts (`cpp_extension.py`). Maybe you are missing a compiler?

Can you try this on Ubuntu?

In any case, this error is unrelated to my original issue and you will probably also run into problems compiling any other touch extension.

**Comment by dudiaoxifenglie** [comment]
> Ok, I forgot to compile the `alt_cuda_corr` module but the `import alt_cuda_corr` was still successful.
> 
> Compiling via `python3 setup.py install --user` inside `alt_cuda_corr` does the trick.
> 
> I would recommend doing the `import alt_cuda_corr` only if the `AlternateCorrBlock` is used and throw an error if the module has not been compiled.

Hello, Sir. I do this like you. But, fails:
![2022-10-13 10-27-52 的屏幕截图](https://user-images.githubusercontent.com/62942271/195484673-c7a484a8-fcdd-4cd9-8594-f9ec370bb81b.png)
